server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    contexts: dev
    enabled: true
